name: Test Python Script on Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Set UTF-8 Encoding  # 인코딩 강제 변경
        run: chcp 65001

      - name: Create virtual environment
        run: python -m venv myenv

      - name: Install dependencies
        run: |
          myenv\Scripts\activate
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          myenv\Scripts\activate
          python main.py
